"COLUMN_NAME","ID"

INSERT INTO lis_order (
    "MESSAGE_DT","ORDER_CONTROL","PID","PNAME","ADDRESS1","ADDRESS2","ADDRESS3","ADDRESS4","PTYPE","BIRTH_DT","SEX","ONO","REQUEST_DT","SOURCE","CLINICIAN","ROOM_NO","PRIORITY","COMMENT","VISITNO","ORDER_TESTID","FLAG"
) VALUES (
    DATE_NOW(), CA, "PID0001", "TEST PASIEN", "ADDRESS1", "ADDRESS2","ADDRESS3","ADDRESS4", "PTYPE", 
)


